# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#{ config, lib, pkgs, modulesPath, ... }:

{self, inputs, ... }:{
  flake.nixosModules.VulperyxHardware = { config, lib, pkgs, modulesPath, ...}: {
    imports =
      [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/f024b2e5-3f61-4a75-9a94-d6d19a40ca47";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/565C-D638";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    fileSystems."/home" =
      { device = "/dev/disk/by-uuid/09265c81-f3de-45a0-85f5-e987ee01cfe2";
        fsType = "ext4";
      };

    fileSystems."/mnt/slowHome" =
      { device = "/dev/disk/by-uuid/750e2aa6-eb35-47b5-8b9d-d1509bcc167b";
        fsType = "ext4";
      };

    swapDevices = [ ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };

}
